name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker images
      run: docker build . --file Dockerfile --tag backend:$(date +%s)
      working-directory: backend
      
    - name: Build the frontend Docker image
      run: docker build . --file Dockerfile --tag frontend:$(date +%s)
      working-directory: frontend
