name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the backend Docker images
      run: docker build . --file backend/Dockerfile --tag backend:$(date +%s) 
      
    - name: Build the frontend Docker image
      run: docker build . --file frontend/Dockerfile --tag frontend:$(date +%s) 
